{% set name = "types-termcolor" %}
{% set version = "1.1.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-termcolor-{{ version }}.tar.gz
  sha256: d8f0f69cf5552cc59ce75aa5172937cec9b320c17453adefe4168b93d16daad6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/termcolor-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for termcolor
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
